test_task:
  container:
    image: rust:latest
  registry_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script:
      - rustc --version
      - cat Cargo.toml
  install_script:
    # these dependencies are for building the kcov tool
    - apt-get update && apt-get install -y --no-install-recommends binutils-dev cmake libcurl4-openssl-dev zlib1g-dev libdw-dev libiberty-dev python
  test_script:
    - cargo test
    - cargo build --features=examples --examples
  coverage_script:
    - ci/upload-coverage
  before_cache_script: rm -rf $CARGO_HOME/registry/index
