language: rust
cache: cargo
script:
  - |
      cargo test &&
      cargo build --features=examples --examples

rust:
  - stable
  - beta
matrix:
  allow_failures:
    - rust: beta

addons:
  apt:
    packages:
      - binutils-dev
      - libcurl4-openssl-dev
      - zlib1g-dev
      - libdw-dev
      - libiberty-dev

after_success:
  - ci/upload-coverage
